### ISSUE TITLE
SQL syntax error

### ISSUE THREAD

**Issue by horrorfodrasz** [paylike/plugin-opencart#12]
After successful bank card payment we got the following error log. (it happen in case of HUF and EURO payment, too)
 PHP Notice: Error: You have an error in your SQL syntax; check the maual that corresponds to your MariaDB server version for the right syntax to use near ’order SET order_id=’2’ WHERE ’order_id’ = ’5261’ at line 1 <br/>Error No.:1064<br/>UPDATE order SET order_status_id=’2’ order_id=’5261’ in /home/…/system/library/db/mysqli.php on line 41

database server:
Server: Localhost via UNIX socket
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.3.25-MariaDB-cll-lve - MariaDB Server
Protocol version: 10
User: 
Server charset: cp1252 West European (latin1)

web server:
Apache/2
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - 
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 7.3.25

phpMyAdmin:
Version information: 4.9.7, latest stable version: 5.0.4

Opencart:
version: 2.0.3.1
Language: Hungarian/English
Currency: HUF/EURO

During test payments the language and currency was HUN/HUF and HUN/EURO (same result in both case)

Error log happen only after successfuly finished payment (after we clicked pay and accepted our bank 3D secure window) and we returned to our homepage.

**Comment by horrorfodrasz** [comment]
Additional info:
I guess it is related to order status. I set  the order status in admin to 'Paid' but after payment it remain as 'process'.
According to the error log "...’order SET order_id=’2’ WHERE ’order_id’ = ’5261’ at line 1"  your extension wants to modify the real 5261 order_id with value 2 (maybe it is the wrong order_status id)
![paylike_error2](https://user-images.githubusercontent.com/63305175/104762577-e1b4ca00-5764-11eb-967a-78f01f2801c7.jpg)

**Comment by horrorfodrasz** [comment]
I found the SQL error message bug source:
catalog\controller\payment\paylike.php
correct code:
$this->db->query("UPDATE " . DB_PREFIX . "`order` SET `order_status_id` = '". $status ."' WHERE...
instead of this:
$this->db->query("UPDATE " . DB_PREFIX . "order SET order_status_id = '{$status}' WHERE...

Error log disappeared 

Your payment extension can't update the 'Order status' in email and admin order history. It is always 'process'. It is not updated based on Extensions->Payments->Paylike-> Order status field selection.
![paylike_bug3](https://user-images.githubusercontent.com/63305175/104836037-0450fb00-58ab-11eb-8ce5-94b4875ae155.jpg)

**Comment by horrorfodrasz** [comment]
Ok. I have found this bug, too:
catalog\controller\payment\paylike.php

correct code:
$this->model_checkout_order->addOrderHistory($this->session->data['order_id'], $this->config->get('paylike_order_status_id'), $message);

instead of this code (in two rows):
$this->model_checkout_order->addOrderHistory($this->session->data['order_id'], $this->config->get('config_order_status_id'), $message);

**Comment by cosminbosutar** [comment]
Hello @horrorfodrasz

Thank you for mentioning the errors and fixes.

We will implement the fixes, test the plugin to see if this works and them release a new version.

Thank you!
Cosmin

**Comment by cosminbosutar** [comment]
Hello @horrorfodrasz

Could you please tell us the exact PHP configuration that you have?

We are interested in the PHP version the exact PHP extensions that you have installed.
You can extract this by running the below script:
`<?php
  echo phpinfo();
?>`

Thank you!
Cosmin

**Comment by ionutcalara** [comment]
I am closing this, but feel free to reopen.
