### ISSUE TITLE
Recurring support for OpenCart

### ISSUE THREAD

**Issue by timarmatyas** [paylike/plugin-opencart#13]
Dear Developer,

We would like use Recurring Payment Profiles in OpenCart, as soon as possible. Do you can can implement that function for us?

Greetings,
Matyas Timar

**Comment by ionutcalara** [comment]
Hi @timarmatyas is this issue intended for OpenCart 2.* ?

**Comment by timarmatyas** [comment]
No, I use OpenCart 3.0.3.3. How can I setup that?

**Comment by ionutcalara** [comment]
the repo for 3.* is this one: https://github.com/paylike/plugin-opencart-3. Do you mind creating the issue there please again?
At this time, we do not have an integration, but we're going to look into it. Please open an issue there, and the OpenCart dev will get back to you.
