### ISSUE TITLE
Is this plugin working on Opencart 2.3.x

### ISSUE THREAD

**Issue by cristibucur90** [paylike/plugin-opencart#4]
Hello,
I have an OC 2.3.x shop and I installed this extension but it doesn't show me any button in payment step.

Did anybody managed to use it into OC 2.3.x?

Thank you
Cristi

**Comment by ionutcalara** [comment]
Hi, @cristibucur90  we are working on creating a separate version for 2.3 we estimate having this ready for live usage by the end of next week at most, but it can also be sooner.

**Comment by cristibucur90** [comment]
Hi @ionutcalara, thank you for your answer. Great to hear that. Keep in touch for the new module. Have a nice day.

**Comment by ionutcalara** [comment]
A new version has been released that is compatible with OC 2.3, you should be able to find it here: https://github.com/paylike/plugin-opencart-2.3

**Comment by cristibucur90** [comment]
Greaat news :D thank you @ionutcalara
