### ISSUE TITLE
Please make an updated OC2.0.31 extension

### ISSUE THREAD

**Issue by horrorfodrasz** [paylike/plugin-opencart#9]
Hi,
I try to install Paylike Opencart extension to my OC2.0.3.1 system.
It seems it is works, but it gives wrong total value in case of Hungarian language. 
I think the problem is that marking of thousend separator is different in english and in hungarian version.
Eng: 1,000.0Euro (one thousend)
Hun:1.000,0Euro (one thousend)
I can send you screenshot and my ocmod installer, too.

Could you please make a fixed version of this extension? Could you please convert your latest OC3 extension to my OC2.0.3.1 version?
Maybe the problem is this line in catalog/controller/payment/paylike.php?
$total = number_format(str_replace(',', '', $total), 2, ".", "") * $multiplier;

Another request/question:
Is there any way to accept more currency with different bank accounts? Make it to support multi currency and multi language? I have separate bank account for EUR and HUF. Both of them linked to my Paylike account. Unfortunately in case of two bank account there is two different public key and app key. 
 
Thank you for your help,

**Comment by cosminbosutar** [comment]
Hello @horrorfodrasz,

Thank you for raising this.

We will have a look at the thousands separator and I'll come back to you here.

Thank you!
Cosmin

**Comment by horrorfodrasz** [comment]
Thank you for your help. 
In addition could you please update it to same functionality as your latest OC2.2/OC3 Paylike extension?

**Comment by ionutcalara** [comment]
Hi @horrorfodrasz while we are looking to patch bugs, opencart 2.* is no longer receiving updates from the opencart team, so we will not actively develop the plugin with new features, only bug fixes. We focus on the latest framework versions as those have better security. We will let you know when the thousands separator issue is fixed.

**Comment by horrorfodrasz** [comment]
Hi Ionut, Maybe OC2 series wont be updated by Opencart team but we are customer of Paylike and we use Opencart 2.0 system. Unfortunately every Opencart version is a dead end. Almost impossible or very expensive to update (e.g extensions need update, too) . So please update the functionality too. 
We are also waiting for the bug fix. We can not use Paylike payment until fixing. Thank you,

**Comment by horrorfodrasz** [comment]
Hi Ionut. I have seen your code modification in code history. I know the code is not finished, but I would like to riport an existing roundig bug that is exists in your latest version.
In case of Hungarian language and Euro combination the total in Euro is rounded (down 10.8 to 10). In case of Euro the rounding is not preferable. In case of HUF and English language it is ok. 
So it is almost ok. I hope I was able to help. 
![paylike_issue2](https://user-images.githubusercontent.com/63305175/103766410-1915cf00-501f-11eb-8907-e8938db8c649.jpg)

**Comment by ionutcalara** [comment]
Hi @horrorfodrasz a new release has been published which fixes the rounding issues. Please test and let us know if you still have issues. 
As for providing feature updates, I am afraid that is something we cannot provide. We are focusing on the latest frameworks versions as those are more secure, and we encourage upgrading for increased security. 

Feel free to reopen the issue if you have issues with the update.
